### PR TITLE
Add new entry for next session 210

### PR DESCRIPTION
**Pull request by itmard**

### CODE REVIEW

**Comment by itmard** [comment]
@ashkang I don't have jdate on osx

**Comment by ashkang** [comment]
If you're using homebrew, trying brew install jcal.

**Comment by itmard** [comment]
@ashkang Thanks.

**Comment by ashkang** [comment]
The reason behind using a single automation script is to write something (hopefully in the near future) that handles sending a message over twitter, Facebook, SMS (AxonSMS has a nice SOAP API by the way), etc. This flow saves a lot of time in maintenance and public announcement process which apparently is a painful one for contributors to TehLUG.

**Pull request merged**
